---
title: "pilot"
author: "REACH BGD"
date: "2 July 2019"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message=FALSE,
                      warning = FALSE)
library(dplyr)
library(hypegrammaR)
library(kableExtra)
source("functions.R")
source("severity.R")
source("refugee_severity_bgd_msna18.R")
#'  READ INPUT FILES

host_assessment <- load_assessment(data_csv = "./input/HCMSNA_csv/HC_HH_Data.csv",
                                   loops_csv = c(individuals = "./input/HCMSNA_csv/HC_Indiv_Data.csv"),
                         questions_csv = "./input/HCMSNA_csv/questions_hc.csv" ,
                           choices_csv = "./input/HCMSNA_csv/choices_hc.csv",
                           samplingframe_csv = "./input/HCMSNA_csv/samplingframe.csv",
                           data.stratum.column = "union_name",
                           sampling.frame.population.column = "NbHH",
                           sampling.frame.stratum.column = "union_id",
                         
                           default_disaggregation = "union_name",
                           asdf = "xasdf")
View(host_assessment$data)

refugee_assessment <- load_assessment(data_csv = "./input/RefugeeMSNA_csv/Refugee_MSNA_HH.csv",
                                      loops_csv = c(individuals = "./input/RefugeeMSNA_csv/Refugee_MSNA_Indiv_Data.csv"),
                                      questions_csv = "./input/RefugeeMSNA_csv/questions_refugee.csv" ,
                                      choices_csv = "./input/RefugeeMSNA_csv/choices_refugee.csv",
                                      samplingframe_csv = "./input/RefugeeMSNA_csv/samplingframe_refugee.csv",
                                      data.stratum.column = "camp_location",
                                      sampling.frame.population.column = "Total.Families",
                                      sampling.frame.stratum.column = "Camps",
                                      
                                      default_disaggregation = "camp_location")




# remove non-consent
refugee_assessment$data <- refugee_assessment$data[refugee_assessment$data$survey_consent=="yes",]
host_assessment$data <- host_assessment$data[host_assessment$data$survey_consent=="yes",]

# CALCULATE SEVERITY 

host_assessment$severity <- host_severity_bgd_msna18(hh = host_assessment$data,
                                                     host_assessment$loops$individuals)




refugee_assessment$severity <- refugee_severity_bgd_msna18(hh  = refugee_assessment$data,
                                                           ind = refugee_assessment$loops$individuals)

# PARAMETERS

attach(refugee_assessment)
  
```



# Severity Scoring Pilot

## Summary

### Results by Union

Distribution of severity:

```{r,fig.height = 20}

ggplot(data)+
  geom_bar(aes(x=overall_severity))+
  theme_minimal()+
  facet_grid(rows = vars(data[[default_disaggregation]]))


```

The estimated severity in the host community:





```{r}
type_of_analysis<-map_to_case("group_difference",
                  dependent.var.type = "categorical",
                  independent.var.type = "categorical")


severity_disaggregated <- map_to_result(data,dependent.var = "overall_severity",
                                        independent.var = default_disaggregation,
                                        case = type_of_analysis,
                                        weighting = weighting)

severity_disaggregated %>%
  map_to_labeled(questionnaire) %>% 
  map_to_table %>% kable %>% kable_styling()

```


```{r}

severity_disaggregated %>%
  map_to_labeled(questionnaire) %>% 
  map_to_visualisation %>% .$ggplot


```

### Distribution - How 'varied' are the scores?
```{r}
design<-map_to_design(data,weighting_function =  weighting)
standard_deviation <- sqrt(survey::svyvar(~overall_severity,design)[1])
```
The overall standard deviation was <b> `r standard_deviation` </b>
```{r}



```

```{r}
ecdf <- weighted_ecdf(data$overall_severity, weighting(data))

ggplot(ecdf, aes(x, cum.pct)) + geom_line() + theme_minimal() + ylab("Cummulative probability") + xlab("Score")

```

## Results

## Methodology

## Conclusion



